describe('Complete Sprint tests', () =>{
    it('Add text to boxes', () =>{
        cy.visit('http://localhost:3001/pizza')
        cy.url().should('include', 'localhost')
        cy.get('input[name="username"]')
            .type('Nova')
            .should('have.value', 'Nova')
        cy.get('input[name="instructions"]')
            .type('Extra Sauce pls!')
            .should('have.value', 'Extra Sauce pls!')
    })
    it('Select Multiple Toppings', () =>{
        cy.get('input[name="beef"]')
            .check()
            .should('be.checked')
        cy.get('input[name="cheese"]')
            .check()
            .should('be.checked')
        cy.get('input[name="pineapple"]')
            .check()
            .should('be.checked')
    })
    it('Add Size', () =>{
        cy.get('select')
            .select('xl')
    })
    it('Submit Form', () =>{
        cy.get('.submitBtn')
            .click().should('be.disabled')
        cy.get('input[name="username"]')
            .should('not.have.value')
        cy.get('input[name="instructions"]')
            .should('not.have.value')
        cy.get('select')
            .should('not.have.value')
        cy.get('input[name="beef"]')
            .should('not.have.value')
        cy.get('input[name="cheese"]')
            .should('not.have.value')
        cy.get('input[name="pineapple"]')
            .should('not.have.value')
    })

})
